name: Python Script Execution

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "55 */5 * * *"

env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  MODAL_BEARER_TOKEN: ${{ secrets.MODAL_BEARER_TOKEN }}
  MODAL_URL: ${{ secrets.MODAL_URL }}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.14"
          enable-cache: true

      - run: uv sync --frozen

      - name: Execute Python script
        run: uv run python main.py
