name: Python Script Execution

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "55 */5 * * *"

env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true

      - run: uv pip install --system -r requirements.txt

      - name: Execute Python script
        run: uv run --no-project python main.py
